### ISSUE TITLE
香橙派5 Openfyde OS 无法在NVME固态硬盘上安装

### ISSUE THREAD

**Issue by Xramyun** [openFyde/overlay-orangepi5-openfyde#13]
![IMG20230401175949](https://user-images.githubusercontent.com/90561372/229280596-e430cb56-63af-4570-b815-9f7169421d76.jpg)
在安装是无法正常安装，但可以试用
我使用的固态是梵想S500PRO
SD卡可以正常使用
Openfyde OS 版本为R108
![IMG20230401180045](https://user-images.githubusercontent.com/90561372/229280721-718aa272-2361-48c8-95a3-457f574849d4.jpg)

![IMG20230401180030](https://user-images.githubusercontent.com/90561372/229280684-feadf0a7-052c-46a1-a1de-e6410e8be109.jpg)

![IMG20230401180015](https://user-images.githubusercontent.com/90561372/229280638-149dbb58-f3f9-42dd-9580-eb42fa568e45.jpg)

**Comment by Damenly** [comment]
请问你加了`—boot sata`参数了吗

**Comment by Xramyun** [comment]
> 请问这个硬盘能在Orangepi5的官方系统上识别的吗？

可以

**Comment by Damenly** [comment]
麻烦提供下
 按下ctrl + alt + f2，用root登录，然后输入 `lsblk` 看下输出，以及 `ls -l /mnt/stateful_partition/fyde/` `dmesg | grep -i nvme`的输出。

**Comment by Xramyun** [comment]
> 麻烦提供下 按下 ctrl + alt + f2，用root登录，然后输入 看下输出，以及 的输出。`lsblk``ls -l /mnt/stateful_partition/fyde/``dmesg | grep -i nvme`

好的

**Comment by Xramyun** [comment]
> 麻烦提供下 按下 ctrl + alt + f2，用root登录，然后输入 看下输出，以及 的输出。`lsblk``ls -l /mnt/stateful_partition/fyde/``dmesg | grep -i nvme`

![IMG20230402083246](https://user-images.githubusercontent.com/90561372/229324223-7fe41377-8eb8-4215-ab65-b31e002e320c.jpg)
![IMG20230402083334](https://user-images.githubusercontent.com/90561372/229324227-8ac946eb-c4ab-4ceb-a2db-0c2426c76108.jpg)
![IMG_20230402_083459](https://user-images.githubusercontent.com/90561372/229324228-d7437d2f-e5e0-4514-b757-7776a5b6fb62.jpg)

**Comment by Damenly** [comment]
你应该是直接把生成的image刷到nvme？类似https://github.com/openFyde/overlay-orangepi5-openfyde/issues/8
因为我们的预设是使用TF卡安装到NVME, 你直接在nvme试用就可以，不会影响实际体验。

**Comment by Damenly** [comment]
另外这个版本开机的时候会有机率无法从NVME启动，我们会在下个版本解决该问题。

**Comment by Xramyun** [comment]
> 另外这个版本开机的时候会有机率无法从NVME启动，我们会在下个版本解决该问题。

谢谢
