### ISSUE TITLE
trying to upgrade to 108

### ISSUE THREAD

**Issue by 333337lee** [openFyde/overlay-orangepi5-openfyde#15]
I tried a linux device Pi4

 and the orange pi5 running openfyde 102 running Linux

@penguin    chmod +x ./orangepi5-openfyde-r108.run --boot nvme 

message unrecognized option '--boot'

will there be a 108 version we can clean install?

thank you

**Comment by Damenly** [comment]
It should be:
`chmod +x ./orangepi5-openfyde-r108.run` and `./orangepi5-openfyde-r108.run --boot nvme`.
Openfyde doesn't support OTA and there will be a new release in few days please wait.

**Comment by 333337lee** [comment]
> It should be:
> `chmod +x ./orangepi5-openfyde-r108.run` and `./orangepi5-openfyde-r108.run --boot nvme`.
> Openfyde doesn't support OTA and there will be a new release that brings up many features and fixups in a few days please wait.

Thank you

I look forward to the next release.

just out of interest, should I have been using Openfyde 102 and running the above command in Linux?

**Comment by Damenly** [comment]
> > It should be:
> > `chmod +x ./orangepi5-openfyde-r108.run` and `./orangepi5-openfyde-r108.run --boot nvme`.
> > Openfyde doesn't support OTA and there will be a new release that brings up many features and fixups in a few days please wait.
> 
> Thank you
> 
> I look forward to the next release.
> 
It's available now.

> just out of interest, should I have been using Openfyde 102 and running the above command in Linux?

If you just want the extracted .img then it's fine.

**Comment by 333337lee** [comment]
> > > It should be:
> > > `chmod +x ./orangepi5-openfyde-r108.run` and `./orangepi5-openfyde-r108.run --boot nvme`.
> > > Openfyde doesn't support OTA and there will be a new release that brings up many features and fixups in a few days please wait.
> > 
> > 
> > Thank you
> > I look forward to the next release.
> 
> It's available now.
> 
> > just out of interest, should I have been using Openfyde 102 and running the above command in Linux?
> 
> If you just want the extracted .img then it's fine.

thank you, the new image is also a .run file. should it be?

**Comment by Damenly** [comment]
Yes, it is.
