### ISSUE TITLE
108r can not activate gapps.

### ISSUE THREAD

**Issue by thadeustr** [openFyde/overlay-orangepi5-openfyde#17]
108r can not activate gapps.
it says "your fydeos does not support this action..."

**Comment by Damenly** [comment]
Yet another in our todo list.

**Comment by Damenly** [comment]
Fixed in r108-r1 already.

**Comment by dirathea** [comment]
hey @Damenly, I've tried the latest version 108r-2 and got the same issue.

![Open Gapps not supported image](https://github.com/openFyde/overlay-orangepi5-openfyde/assets/1830284/465c8010-ce9e-4906-b8a5-88e9967cf5eb)

![image](https://github.com/openFyde/overlay-orangepi5-openfyde/assets/1830284/88a3798b-d801-4f85-a37f-668498a669e2)

**Comment by Damenly** [comment]
Sorry for the wrong information. Opengapps is not supported in the version.

**Comment by Damenly** [comment]
The Archero of the new version brings microG as an alternative to Gapps. You can try it.
