### ISSUE TITLE
Official WiFi add-on module, is it supported on OpenFyde?

### ISSUE THREAD

**Issue by vanfanel** [openFyde/overlay-orangepi5-openfyde#19]
Hi there,

I have just booted OpenFyde on the Orange Pi 5, which has the official WiFi module add-on installed, but it's not detected on boot. Is it supported? 

This is the chip it uses:
https://www.sparklan.com/product/ap6275p-broadcom-sip-module/

This is the module they are selling:

https://es.aliexpress.com/item/1005005383810227.html?spm=a2g0o.order_list.order_list_main.11.1378194dOt1ikn&gatewayAdapt=glo2esp

Thanks!

**Comment by vanfanel** [comment]
EDIT: On GNU/Linux (DietPi) it uses an overlay to work.
Adding this line to /boot/dietpiEnv.txt works:
overlays=opi5-wifi-ap6275p

I hope it helps in order to get this official add-on supported in OpenFyde.

**Comment by Damenly** [comment]
There’s a mistake I made in kernel config so even you apply the dtbo it won’t work.

**Comment by vanfanel** [comment]
> There’s a mistake I made in kernel config so even you apply the dtbo it won’t work.

Ah, ok, so next version will support the official WiFi add-on (ap6275p) ??

**Comment by Damenly** [comment]
Yes.
