### ISSUE TITLE
wifi+bluetooth usb dongle device not working

### ISSUE THREAD

**Issue by avatar21** [openFyde/overlay-orangepi5-openfyde#2]
wifi+bluetooth usb dongle device (RTL8723BU) not working, it's working both in official Oragepi repo and Armbian.

**Comment by Damenly** [comment]
Thanks for reporting. Will be fixed in next release.

**Comment by Damenly** [comment]
Please try the new release image.

**Comment by Damenly** [comment]
Close cause a long time for no feedback.
