### ISSUE TITLE
RTL8188EUS support in OpenFyde

### ISSUE THREAD

**Issue by vanfanel** [openFyde/overlay-orangepi5-openfyde#20]
Hi there,

I have this other WiFi USB adapter:
`
Bus 001 Device 016: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter`

which works fine on GNU/Linux, but OpenFyde doesn't seem to detect it either..
Is it supposed to work?

Thanks

**Comment by Damenly** [comment]
We’ll take it into next release. Soon.

**Comment by vanfanel** [comment]
@Damenly Oh thanks!

What about the official one? --> https://github.com/openFyde/overlay-orangepi5-openfyde/issues/19

I can't even get it to work on GNU/Linux.

**Comment by vanfanel** [comment]
EDIT: On GNU/Linux (DietPi) it uses an overlay to work.
Adding this line to `/boot/dietpiEnv.txt` works:
`
overlays=opi5-wifi-ap6275p
`

I hope it helps in order to get this official add-on supported in OpenFyde.

**Comment by vanfanel** [comment]
I see there's this already on the OpenFyde system:
`
ROOT-A/boot/rockchip/overlay/rk3588-wifi-ap6275p.dtbo`

So, the only question now is: How can I enable an overlay in OpenFyde?

**Comment by Damenly** [comment]
Please try the new r108-r2.
