### ISSUE TITLE
[QUESTION] What OpenGL/Vulkan implementation does openfyde use?

### ISSUE THREAD

**Issue by vanfanel** [openFyde/overlay-orangepi5-openfyde#21]
Hi there,

My main reason to use OpenFyde is to find out if it supports Vulkan.

I can't find any info about the 3D acceleration implementation used by OpenFyde: Does it use MESA Panfork/Panfrost, which is limited to OpenGL/GLES? Or does it use the binary-only drivers?

Is Vulkan supported somehow on OpenFyde on the Orange Pi 5?

Thanks

**Comment by Damenly** [comment]
Yes OpenGLES. Rockchip has no plan for support vulkan for now.
