### ISSUE TITLE
MediaTek MT7610U

### ISSUE THREAD

**Issue by martinbone** [openFyde/overlay-orangepi5-openfyde#22]
Any chance of support for the above chipset (for Archer T2U V3 wifi dongle)?

**Comment by Damenly** [comment]
Does it work on armbian? And any external setup instructions?

**Comment by martinbone** [comment]
> Does it work on armbian? And any external setup instructions?

Yes, it works straight away on Armbian (didn't need to install or configure anything, except the actual connection to my WiFi network). I saw another GitHub page about the chipset. Will try to find again to post here ...

**Comment by martinbone** [comment]
Not sure if this is useful - but there's reference to the driver and ChromeOS:

https://github.com/sebanc/brunch/issues/513

**Comment by Damenly** [comment]
Please try the new r108-r2. I don't know if it helps so expect your feedback

**Comment by Damenly** [comment]
Thanks for your reply.
