### ISSUE TITLE
Not clear how to update to a new version

### ISSUE THREAD

**Issue by saulgodino** [openFyde/overlay-orangepi5-openfyde#23]
I have the R102 version installed e want to install the new version R108-R1. How can I update my current version to  the new, keeping my configs and installed apps?

**Comment by Damenly** [comment]
openfyde doesn't support OTA updates for many reasons. I'm afraid you have to reinstall your OS.

**Comment by Damenly** [comment]
The new r114 version supports further version local OTAs. Recommend to install.
