### ISSUE TITLE
Orange pi 5b - emmc

### ISSUE THREAD

**Issue by enissayol** [openFyde/overlay-orangepi5-openfyde#28]
Hello,

I can't install this distribution on the orange pi emmc, when i execute the command and remove the sd card the orange pi won't boot.

Thanks

**Comment by Damenly** [comment]
Hi,

Thanks for your report. You mean the device won't boot after you click the installation in the image made by `./orangepi5-openfyde-r108-r2.run   --boot emmc`?  If so, it's a bug even Orange pi 5b support is experimental.

**Comment by Damenly** [comment]
You can try the new version.
