### ISSUE TITLE
Usb type-C + type-A port (so-called shared ports) not working

### ISSUE THREAD

**Issue by avatar21** [openFyde/overlay-orangepi5-openfyde#3]
Usb type-C + type-A port (so-called shared ports) not working, same it's working in Armbian latest release (hot and cold plug mode).

**Comment by Damenly** [comment]
Not understood. Could you elaborate more please?

**Comment by avatar21** [comment]
Means I tried r102 OpenFyde image on Orange PI 5 device, the usb-type c and vertical USB A port are shared (as per Orange PI document), they both no usable.
However I'm telling you it working perfectly or Amrbian Linux, official Orange OSes (including Android), may be you could take a look at how they did it.
