### ISSUE TITLE
 FydeOS v16 "Existential blossom" incorrect android version

### ISSUE THREAD

**Issue by develperbayman** [openFyde/overlay-orangepi5-openfyde#31]
using 114 build says android 11 but is actually android 9

**Comment by Damenly** [comment]
Would you please rephrase your issue? I can’t understand your problem.

**Comment by develperbayman** [comment]
thats basically it it says android 11 in the release but its actually running android 9

**Comment by Damenly** [comment]
I guess you mixed up FydeOS and openFyde? FYI: https://github.com/openFyde/getting-started#tldr-in-faq-format

openFyde for rk3588(s) SBCs are with Archeo (Android 11 container).
FydeOS for rk3588(s) SBCs are with Arcplus (Android 11 container).

**Comment by develperbayman** [comment]
holy cow i think your right .... my bad  ...the disadvantages of distro hopping lol

**Comment by Damenly** [comment]
That’s okay. Feels free to ask.
