### ISSUE TITLE
R114, Could not select SATA SSD on OrangePi5

### ISSUE THREAD

**Issue by osakanataro** [openFyde/overlay-orangepi5-openfyde#34]
I have OranegePi5 and NVMe SSD, SATA SSD.
In R114 image, 
"./orangepi5-openfyde-r114.run --board orangepi5 --boot nvme" install success to NVMe SSD.
"./orangepi5-openfyde-r114.run --board orangepi5 --boot sata" disk not found, could not select SATA SSD or NVMe SSD.

**Comment by Damenly** [comment]
Weird. I reconfirmed SATA SSD can be detected on my orangepi5. Does it work normally in the previous version?

**Comment by HuangJiew** [comment]
我我也遇到了

**Comment by osakanataro** [comment]
In R114-R1, it could select sata ssd.
and boot success from sata ssd.

**Comment by HuangJiew** [comment]
> 在R114-R1中，它可以选择sata ssd。以及从SATA SSD启动成功。

谢谢

**Comment by Damenly** [comment]
I guess I can close the issue?

**Comment by HuangJiew** [comment]
> 我想我可以关闭问题吗？

问题依旧存在，全盘安装，选择不了磁盘
