### ISSUE TITLE
rtl8821CU not working

### ISSUE THREAD

**Issue by IsQiao** [openFyde/overlay-orangepi5-openfyde#4]
usb wifi device `COMFAST 811AC` not working. 
it is  `rtl8821CU` chip.
could you please add this driver to the image?
thanks 😸

**Comment by Damenly** [comment]
Noted. Thanks for your report.

**Comment by Damenly** [comment]
Please try the new image.

**Comment by IsQiao** [comment]
thanks a lot. 😁
