### ISSUE TITLE
Proposal for r108 script

### ISSUE THREAD

**Issue by chinen95** [openFyde/overlay-orangepi5-openfyde#6]
Thank you for your work!
The shell used in r108 script is `#!/bin/sh`, but the code was writen for bash.
When running on Ubuntu with default settings, the following error will be reported:
`./orangepi5-openfyde-r108.run --boot sata`
`./orangepi5-openfyde-r108.run: 53: [: sata: unexpected operator`
`./orangepi5-openfyde-r108.run: 56: [: sata: unexpected operator`
`--boot requires an argument`
Because the `/bin/sh` is linked to `dash` in ubuntu by default.
Is it better to change it to `#!/bin/bash` to make it less likely that errors will occur?

**Comment by Damenly** [comment]
Oh.. Indeed.  Fixed and release image was updated. It also fixes badness in MacOS because its `echo` of /bin/sh doesn't support `-n`.

**Comment by chinen95** [comment]
Thank you for fixing the issue quickly!
